# Generated by Django 5.0.7 on 2024-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TreeMenu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treemenu",
            name="slug",
            field=models.CharField(default="slug", max_length=50),
        ),
    ]
