# Generated by Django 5.0.7 on 2024-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TreeMenu", "0002_treemenu_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treemenu",
            name="slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
